### ISSUE TITLE
ModuleNotFoundError: No module named 'gspread.models'

### ISSUE THREAD

**Issue by burhanshah** [robin900/gspread-dataframe#43] opened 2022-02-17 10:23 UTC
I am getting this error, what should I do ? I am using google colab

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-61-a16ddb767c75> in <module>()
      1 [#Export](https://www.youtube.com/hashtag/export) to Google Sheets / Part 2 Export
----> 2 from gspread_dataframe import get_as_dataframe, set_with_dataframe
      3 
      4 sh = gc.create('filename')
      5 worksheet = gc.open('filename').sheet1

/usr/local/lib/python3.7/dist-packages/gspread_[dataframe.py]() in <module>()
     11 """
     12 from gspread.utils import fill_gaps
---> 13 from gspread.models import Cell
     14 import logging
     15 import re
```

**Comment by robin900** [comment] 2022-02-17 14:15
@burhanshah what version of gspread are you using?

**Comment by robin900** [comment] 2022-02-17 14:24
@burhanshah I see, this is the import problem solved by release 3.2.2 of gspread-dataframe. Make sure you are using 3.2.2, the latest version of gspread-dataframe, and you will be ok. Please let me know if upgrading solves your problem.

**Comment by robin900** [comment] 2022-02-17 15:54
@burhanshah Here is what I get for `!pip list -v` in a brand new Google Colab notebook:

![image](https://user-images.githubusercontent.com/325578/154518568-f7470cbf-6b2d-411b-bb22-4bf3f23828c6.png)

Note that gspread is version 3.4.2; the corresponding version of gspread-dataframe (3.0.8) should work just fine.

Is your notebook using a more recent gspread version? If it's >=5.0.0, then you will have to upgrade gspread-dataframe to 3.2.2.

**Comment by robin900** [comment] 2022-02-18 15:48
@burhanshah Has your problem been resolved?

**Comment by robin900** [comment] 2022-02-20 16:44
Closing this issue, since the cause has been discovered and need not be solved by any code changes or releases.

**Closed by robin900** 2022-02-20 16:44 UTC

**Comment by SharonGutierrezCH** [comment] 2023-11-06 23:00
hi @robin900 I have exactly the same problem as him, I've already searched the entire internet looking for a solution and I can't find it.
I have my latest versions of everything, I already tried it in different envs and nothing.
How can this be resolved?

my versions

gspread               5.12.0
gspread-dataframe     3.2.1
gspread-pandas        3.2.3

**Comment by martin168th** [comment] 2024-10-30 19:07
I was having this issue, none of the solution offered here helped me, for any one reading this in the future, what worked for me was updating gspread-formatting. now I have everyting on their latest version. I really needed add_validation() to work.

**Comment by robin900** [comment] 2024-10-30 19:52
@martin168th Thanks for posting the info!
