### ISSUE TITLE
Bug: Object of type int64 is not JSON serializable - introduced by Version 3.1.1

### ISSUE THREAD

**Issue by bastianwegge** [robin900/gspread-dataframe#31] opened 2020-10-22 16:50 UTC
Hey @robin900 ,
we (@AndreCimander and me) might have found a bug which will lead to the following error.

The error is caused by this commits (https://github.com/robin900/gspread-dataframe/commit/00d2de44b81da78721879633368b9f37db42b5c5) changes in `gspread_dataframe.py:53`. 

As the default `pandas` `DataFrame` will cast an integer to a `numpy.int64`, your changes will cause the JSON parsing to fail with the following set of information to reproduce the error.

Rolling back to version `3.1.0` fixes the issue, as `numpy.int64` is properly casted to a `str` before insertion.

Code:
```
test_dataframe = pd.DataFrame({"column1": [6, 6, 7], "column2": [4, 4, 4]})
[...]
gspread_dataframe.set_with_dataframe(
    worksheet, dataframe, row=start_row, col=1, include_column_header=use_header
)
```

Error message: `TypeError: Object of type int64 is not JSON serializable`

Stack trace:
```
google_sheets_api/sheet.py:85: in append_pandas_dataframe_to_sheet
    gspread_dataframe.set_with_dataframe(
venv/lib/python3.8/site-packages/gspread_dataframe.py:299: in set_with_dataframe
    resp = worksheet.update_cells(cells_to_update, value_input_option='USER_ENTERED')
venv/lib/python3.8/site-packages/gspread/models.py:906: in update_cells
    data = self.spreadsheet.values_update(
venv/lib/python3.8/site-packages/gspread/models.py:235: in values_update
    r = self.client.request('put', url, params=params, json=body)
venv/lib/python3.8/site-packages/gspread/client.py:61: in request
    response = getattr(self.session, method)(
venv/lib/python3.8/site-packages/requests/sessions.py:590: in put
    return self.request('PUT', url, data=data, **kwargs)
venv/lib/python3.8/site-packages/google/auth/transport/requests.py:464: in request
    response = super(AuthorizedSession, self).request(
venv/lib/python3.8/site-packages/requests/sessions.py:516: in request
    prep = self.prepare_request(req)
venv/lib/python3.8/site-packages/requests/sessions.py:449: in prepare_request
    p.prepare(
venv/lib/python3.8/site-packages/requests/models.py:317: in prepare
    self.prepare_body(data, files, json)
venv/lib/python3.8/site-packages/requests/models.py:467: in prepare_body
    body = complexjson.dumps(json)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py:231: in dumps
    return _default_encoder.encode(obj)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py:199: in encode
    chunks = self.iterencode(o, _one_shot=True)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py:257: in iterencode
    return _iterencode(o, 0)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.encoder.JSONEncoder object at 0x7f9038667790>, o = 1

    def default(self, o):
        """Implement this method in a subclass such that it returns
        a serializable object for ``o``, or calls the base implementation
        (to raise a ``TypeError``).

        For example, to support arbitrary iterators, you could
        implement default like this::

            def default(self, o):
                try:
                    iterable = iter(o)
                except TypeError:
                    pass
                else:
                    return list(iterable)
                # Let the base class default method raise the TypeError
                return JSONEncoder.default(self, o)

        """
>       raise TypeError(f'Object of type {o.__class__.__name__} '
                        f'is not JSON serializable')
E       TypeError: Object of type int64 is not JSON serializable

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py:179: TypeError
```

If you need further information or assistance, please let me know.

**Comment by robin900** [comment] 2020-10-22 19:34
Thanks for reporting this problem. It's good that you have a workaround now by pinning to release 3.1.0. 

Other users of this package, whose Google sheets are in non-English locales, suffer when numeric values are stringified in the JSON request, so I'm reluctant to go back to stringifying things as it will make the non-English-locale people suffer again. Also, providing numeric cell values as JSON numeric values is the proper way to use the Sheets API.

So I think I'd like instead to try to support `numpy` scalar types better, by converting them to native Python numeric types before JSON encoding. _Most_ of the numpy numeric types can convert to native Python numerics without loss of precision (`longdouble` being the exception). What do you think about that approach to a solution?

**Comment by robin900** [comment] 2020-10-22 19:42
Pull request #32 contains test coverage (explicitly testing `np.int64`) and code changes to support numpy numeric scalars properly. Would you mind reviewing, @bastianwegge and @AndreCimander ?

**Comment by AndreCimander** [comment] 2020-10-22 21:07
Hi @robin900, thanks for your quick reply. Yeah, I agree, breaking it for the non-english-locale will just create more suffering 👍 

There's a nice JSON-Encoder helper, which seems to cover most of the ground, might be a neat source of inspiration 🙃 https://github.com/hmallen/numpyencoder/blob/master/numpyencoder/numpyencoder.py

**Comment by robin900** [comment] 2020-10-22 21:24
@bastianwegge When testing the pull request further, I'm discovering that at least for my environment (pandas 1.0.3, numpy 1.18.2), calling `set_with_dataframe` uses `DataFrame.values` which does a lot of implicit upcasting of cell values, including from int64 to Python int. Thus I can't actually reproduce the problem you're seeing, since for me a DataFrame with three int64 columns becomes an array of Python int objects and I never see an exception.

Could you post here for me your:
- Python version
- Pandas and NumPy versions

**Comment by bastianwegge** [comment] 2020-10-23 07:22
Hey @robin900, thanks for the immediate response.

Those are the versions we're working with:
- python `3.8.5`
- numpy `1.19.2`
- pandas `1.1.3`

If that's not enough I can set up a testcase later today.

**Comment by robin900** [comment] 2020-10-25 00:02
@AndreCimander Yes, I looked at that `numpyencoder` code, and we could adapt something like it to be a pre-encoding step. But I think that first we need to reach a consensus on the most reliable way to extract values from a DataFrame before sending them to Sheets API. The current reliance on `DataFrame.values` seemed like the right away forward, but now I'm puzzled by the behavior you're seeing. I'll test with your versions of pandas and numpy and see what I can find out...

**Comment by robin900** [comment] 2020-10-26 07:01
@bastianwegge @AndreCimander I've installed all the versions you've mentioned in a test virtualenv, and I'm just not able to reproduce any exception when calling `set_with_dataframe` and a DataFrame whose columns are all of dtype Int64. The reason seems to be that `DataFrame.values` does seem to provide cell values as Python types (int, float) rather than NumPy types. Even `.to_records()` and `.to_numpy()` provide arrays whose elements are Python int. (Examining cell values directly in this dataframe confirms that they are instances of `numpy.int64`.)

Can you provide any more detail about how you are building the DataFrame that causes the exception for you? Can you provide the output of `dataframe.dtypes` and `dataframe.shape` and `dataframe.columns`? I am really stumped here.

**Comment by robin900** [comment] 2020-11-02 16:30
@bastianwegge @AndreCimander I'm going to close this issue until we have some way to reproduce the problem. Let me know if you have that information and want the issue re-opened...

**Closed by robin900** 2020-11-02 16:30 UTC
Labels: bug
